### ISSUE TITLE
Repository Approval Request Jumper-Cogs

### ISSUE THREAD

**Issue by Redjumpman** [Twentysix26/Red-Docs#10]
Repository name: Jumper-Cogs (https://github.com/Redjumpman/Jumper-Cogs)
Author: Redjumpman (Redjumpman#2375 on Discord)
Description: Will be developing mostly cogs related to gaming such as Pokedex.

**Comment by Kowlin** [comment]
Looks fine to me, but note: https://github.com/Redjumpman/Jumper-Cogs#installation
There will be a command included to add the repo to the downloader. it would be the best to change to the following format: `cog install Jumper-Cogs <cogname>`

**Comment by tekulvw** [comment]
There is one thing I noticed. In pokedex you check for the existence of external dependencies but you do nothing with those checks. You need to add helpful messages in the `setup()` function and _not_ let the cog load unless all the required dependencies are installed. Other than that, looks good.

**Comment by irdumbs** [comment]
`/Red-DiscordBot_v2_tag/cogs/downloader.py", line 99, in _send_list
    col_width = max(len(row[0]) for row in retlist) + 2`
getting that ^ on !cog list <your_repo>
will have to take a look to see if that's an issue with downloader.py or your repo

**Comment by Redjumpman** [comment]
@Kowlin I added the installation instruction that you provided to my readme. 
@tekulvw I added the check for dependencies in my setup().
@irdumbs ~~I'm not sure why you are getting that with your downloader.py. It seems to be working fine with me, and I have not edited downloader.py. Have you altered yours?~~ Fixed!

**Comment by Redjumpman** [comment]
@Kowlin There is no longer a conflicting issue with downloader.py. I have renamed the folders.

**Comment by tekulvw** [comment]
You don't need to (and shouldn't) require numpy in pokedex. The functionality you're looking for can be done with a builtin, namely `zip()`

**Comment by irdumbs** [comment]
just something that irks me.
![image](https://cloud.githubusercontent.com/assets/15660809/14872790/078e2df6-0d33-11e6-9625-4a867bcbad2e.png)
the "example" isn't an example, it's just a copy paste of the 1st help line.
suggest putting in an example instead. ex. [p]pokedex moveset 1 pikachu
also, suggest changing the argument name to "pokemon" instead of "text"

**Comment by Redjumpman** [comment]
@irdumb I made the changes you suggested to my .JSON file, renamed my arguments for clarity, and added a real example for each command.
@tekulvw Removing numpy dependency is on my to-do-list, but I'm working on other projects atm. Does this disqualify me from approval of this repo?

**Comment by Redjumpman** [comment]
@tekulvw  @Kowlin @irdumbs I have removed the numpy dependency from my pokedex cog

**Comment by irdumbs** [comment]
\o/  ty.
most of the latter stuff we mentioned doesn't disqualify you. They are just things we found that irk us.
What's stopping me at least from giving approval is just I haven't had time to look through / test your code yet :) 

You've been great at addressing the things we've brought up though, so as long as you continue to improve on your cogs and address things we bring up in the future,
i'll give you my 👍 
Good work.

**Comment by irdumbs** [comment]
one last thing if you don't mind :P
if you're gonna put an install section in your readme, mind listing the dependencies there as well?
or at least where you describe pokedex

**Comment by Redjumpman** [comment]
@irdumbs  I'm still learning, so if you guys are being nit picky, it only helps me from forming bad habits. I don't want my repo approved if it looks like crap, and I've learned a lot from the advice! I'll add the dependencies to the installation section :+1:

**Comment by Redjumpman** [comment]
@irdumbs @tekulvw Everything is done :)
