### ISSUE TITLE
Repository Approval Request Booru-Cogs

### ISSUE THREAD

**Issue by Alzarath** [Twentysix26/Red-Docs#11]
Repository name: Booru-Cogs (https://github.com/Alzarath/Booru-Cogs)
Author: Alzarath
Description: Image booru fetching cogs

This is a migration from a cog that's already in the Community repo. If the pony cog could be removed from the Community repo when this gets approved, that would be appreciated.

I do plan on expanding this and adding more, similar cogs in the future.

**Comment by irdumbs** [comment]
I have a moral objection to this repo,
but no coding objections.

Looks fine to me.
Doesn't have any requirements right?

**Comment by Alzarath** [comment]
No requirements that I'm aware of. I won't pretend I'm some fantastic programmer with experience beyond copying and modifying other cogs' code, though.

**Comment by irdumbs** [comment]
looks fine. I approve. 👍

**Comment by Kowlin** [comment]
+1 from me, awaiting another Red-DiscordBot contributor.

**Comment by FishyFing** [comment]
+2
