### ISSUE TITLE
Cheshire Cogs Repo

### ISSUE THREAD

**Issue by NekoMajo** [Twentysix26/Red-Docs#112]
List: beta
Repository name: Cheshire Cogs
Author: Cheshire
Description: MISC Cogs for Red

**Comment by Stylite** [comment]
This isn't even your code. It's from https://github.com/MadamJazzy/JazzyCogs/blob/master/social/social.py

**Comment by Jan200101** [comment]
Only 1 minor cog
it is not your cog
no major edits to it have been done

**Comment by NekoMajo** [comment]
I pulled it because there was some issues with the cog that I wanted to
hammer out my self. I was not intentionally supposed to be anything that
anyone would download, I just needed to make some changes for my server
that its being used on
