### ISSUE TITLE
Dp-Cogs Repo

### ISSUE THREAD

**Issue by xDp64xG** [Twentysix26/Red-Docs#115]
List: beta
Repository name: [Dp-Cogs](https://github.com/xDp64xG/Dp-Cogs)
Author: xDp64xG
Description: These are just various cogs, nothing too exciting. Only 2 cogs are currently "working", the "Youtube-Announcer" still getting work done to it.

**Comment by Jan200101** [comment]
First off a link to the repo in the original post would be nice.
I [found it](https://github.com/xDp64xG/Dp-Cogs) after some searching.

Then I suggest installing modules using the cog downloader by adding a requirements field to the info.json

I have also noticed that Battleship was written to be used with a specific bot in mind, Tailcog is not restricted and can show sensitive information and that Tailcog relies on OS specific if it was run on Linux.
This would only create more issues on systems without tail
