### ISSUE TITLE
Repo Approval FishyCogs

### ISSUE THREAD

**Issue by franc-ist** [Twentysix26/Red-Docs#12]
https://github.com/FishyFing/FishyCogs

Repository name: FishyCogs
Author: fishyfing
Description: Some coding practice that may have created useful cogs.

**Comment by irdumbs** [comment]
looks fine to me.
👍

**Comment by Kowlin** [comment]
Why don't you just import the whole module from the get go? https://github.com/FishyFing/FishyCogs/blob/master/timezone/timezone.py#L3-L6

**Comment by franc-ist** [comment]
fixed

**Comment by tekulvw** [comment]
Only thing I'd suggest is have a toggle for the message listener in `ayy`

**Comment by franc-ist** [comment]
done @tekulvw
