### ISSUE TITLE
Publishing repo information

### ISSUE THREAD

**Issue by tekulvw** [Twentysix26/Red-Docs#13]
We need to make the process as clear as possible. At the moment it is not clear that the folder name must match the cog file name exactly (capitalization included).

**Comment by Kowlin** [comment]
Will fix it tonight, any more issue's I should be aware off?

**Comment by irdumbs** [comment]
should also update the info_maker to properly explain that "name" should actually be "short description"
unless we want cog lists to look like this in the future:
![image](https://cloud.githubusercontent.com/assets/15660809/14869993/78c5a3be-0d1a-11e6-8a22-865161695401.png)

**Comment by Kowlin** [comment]
I thought I removed that script, @irdumbs

**Comment by irdumbs** [comment]
👍 seems as if you did.
