### ISSUE TITLE
Repo approval request Squid-Plugins

### ISSUE THREAD

**Issue by tekulvw** [Twentysix26/Red-Docs#14]
https://github.com/tekulvw/Squid-Plugins

Repo Name: Squid
Author name: Will
Description: A collection of cogs and tools I find useful
- Added in those pesky prereqs :P

**Comment by irdumbs** [comment]
premature acceptance. sigh, gotta look through code now

**Comment by franc-ist** [comment]
@irdumbs finished looking through the code?

**Comment by irdumbs** [comment]
¯\_(ツ)_/¯
still things missing that'd go against the approval requirements.
missing doc strings in rss at least.
If we keep this open, Will has less 'responsibility' to offer support for these cogs 😉

**Comment by ddday** [comment]
It'd be nice if there we more examples in it

**Comment by tekulvw** [comment]
Feel free to PR them in

**Comment by ddday** [comment]
I don't know much about rss templates... never-mind, if they have the cog they'll probably know how to use a rss feed anyways.

**Comment by tekulvw** [comment]
Welp...already got added and I fixed the docs so I'm gonna go ahead and close this
