### ISSUE TITLE
dylcogs

### ISSUE THREAD

**Issue by daftuyda** [Twentysix26/Red-Docs#140]
List: beta
Repository name: [dylcogs](https://github.com/AmIVoid/dylcogs)
Author: *Void/AmIVoid
Description: Just here making anime commands.

**Comment by Kowlin** [comment]
Hey there, sorry to disappoint. But with the upcoming release of V3, we no longer support adding new repositories on the v2 documentation. If you'd like to apply to the new list you can do so [here](https://cogboard.red). Please note that this only applies for the newer V3 repositories.
