### ISSUE TITLE
Repo approval request Mash-Cogs

### ISSUE THREAD

**Issue by Fr6jDJF** [Twentysix26/Red-Docs#15]
https://github.com/Canule/Mash-Cogs/

**Repository name:** 
Mash

**Author:**
Mash/Canule

**Description:** 
General cogs. 
*oboobs = NSFW

**Comment by franc-ist** [comment]
I have no objections. It all seems to work fine.

**Comment by irdumbs** [comment]
Please make it obvious to the user that they will be using economy.py currency for the drinks.
Please don't edit other cogs' data files.
Please use economy's set/get functions. If they are not sufficient, please let us know or make a PR fixing them.

I know you're currently working on these cogs, but please make sure to put ample help/descriptions if you're putting them up for other people to use.

**Comment by Fr6jDJF** [comment]
@irdumbs 
That bartender thing was a bit to fast released.
It should be fixed by now.

**Comment by irdumbs** [comment]
spiff it up a bit on the help strings n such
make sure you be explicit about what your bot edits and make sure you get permission from the user

+1

**Comment by Fr6jDJF** [comment]
-Added help strings
-Fixed https://gyazo.com/6136a3b25e21f4270406cbfb22fd6b12

**Comment by ddday** [comment]
https://gyazo.com/6136a3b25e21f4270406cbfb22fd6b12

description should be below the async def line.
