### ISSUE TITLE
Repo approval request Eslyium-Cogs

### ISSUE THREAD

**Issue by Eslyium** [Twentysix26/Red-Docs#17]
https://github.com/Eslyium/Eslyium-Cogs

Repository name: Eslyium-Cogs
Author: Eslyium
Description: General Cogs and NSFW Cogs.

**Comment by franc-ist** [comment]
Oh look. Another "network tools" cog. XD

**Comment by franc-ist** [comment]
Network tools is conflicting with Skordy's application #16 . Please sort this out between yourselves.

**Comment by irdumbs** [comment]
hmm..
could we put a nsfw toggle.
the bot owner is the one installing the cog, but the server owners may like their own toggle :3

**Comment by Twentysix26** [comment]
Toggle rule has been removed. Approved for beta list.
