### ISSUE TITLE
Repo approval request anomalys-cogs

### ISSUE THREAD

**Issue by ddday** [Twentysix26/Red-Docs#19]
https://github.com/ddday/anomalys-cogs/

Repository name: anomalys-cogs
Author: anomaly
Description: Fun API cogs.

**Comment by irdumbs** [comment]
the stream one makes me uneasy as it's a PR and will likely be implemented into the bot even if the PR isn't accepted.

the id one.. I just.. don't like...

**Comment by ddday** [comment]
I've been planning to remove stream, and maybe i'll make id a tutorial on
how to get IDs or something.

**Comment by ddday** [comment]
Removed stream and changed ID

**Comment by irdumbs** [comment]
lol the id change.
that cog has now gone from negative to something that will definitely benefit the community 👍

**Comment by Twentysix26** [comment]
Way too little content. The id one is basically a joke. I'm closing this, you can ask for your application to be reviewed again in the future.

**Comment by ddday** [comment]
Agreed, I have been planning to add more cogs but I can't do much about that since my laptop is broken at the moment.

**Comment by irdumbs** [comment]
😢
