### ISSUE TITLE
Repo approval request wolf-cogs

### ISSUE THREAD

**Issue by Wolfieheart** [Twentysix26/Red-Docs#20]
Repository name: Wolf-Cogs
Author: Wolfstorm
Description: General Cogs made for Red
Link to Repo: https://github.com/Wolfst0rm/Wolf-Cogs

**Comment by franc-ist** [comment]
Thanks for submitting this! However, your info jsons are in the old format. Please follow this [new format](https://twentysix26.github.io/Red-Docs/red_cog_info_json/)

**Comment by Wolfieheart** [comment]
Fixed in current version

**Comment by irdumbs** [comment]
hmm these cogs look familiar

**Comment by Wolfieheart** [comment]
Some of them are repurposed code from other scripts within Red-DiscordBot already. Some of them are based on mIRC Coded Languaged Scripts, that I have attempted to try and rebuild functionally for Red.

**Comment by irdumbs** [comment]
not sure what you mean by repurposed.
I'd just prefer you give credit to the original writers if... let's say > 20% is written by someone else
I mean that's not the set rule. just use your discretion 👍

**Comment by Wolfieheart** [comment]
That I will do. Credit where Credit is due and all. Might add it within the actual cog itself and within the Info JSON :) if that's an alright place to put it ofc

**Comment by irdumbs** [comment]
That's where I like to put em. 1 for the users to see and 1 for developers to see

**Comment by Wolfieheart** [comment]
Alrighty, Latest and previous commits has changes :)

https://github.com/Wolfst0rm/Wolf-Cogs/commit/ec38e859cc409ecc7b44cf6804ed1897acaa80fa
https://github.com/Wolfst0rm/Wolf-Cogs/commit/242c79bb593b1941c5d71d7613f67d4670419a0f

**Comment by irdumbs** [comment]
I believe you've forgotten one.

https://github.com/irdumbs/Dumb-Cogs/tree/master/ping

**Comment by Wolfieheart** [comment]
Commit going live now: https://github.com/Wolfst0rm/Wolf-Cogs/commit/da0a66d64b01b86f94b434e653a83c9ad145277b

**Comment by tekulvw** [comment]
Denying because of a lack of original/unique content that benefits the community. Feel free to apply again at a later date.
