### ISSUE TITLE
Let's make separate lists of Repos

### ISSUE THREAD

**Issue by tekulvw** [Twentysix26/Red-Docs#23]
I'm proposing (as others have discussed) to make separate lists of repositories. One list being an "approved" list that contains repos highly beneficial to the community, made by devs who know what they're doing and who will be around to fix things if something happens to break. Admittance to this list will probably be highly subjective, so don't get your feelings hurt :P 

The second list will be a "beta" list that contains repos for anyone who wants their repo to be public and comes with clear warnings that the things found in these repos is entirely unmoderated and not guaranteed to work in any way.

Name suggestions welcome.

**Comment by franc-ist** [comment]
Approved Repos, and Fishy's Broken Stuff? Kappa

![](http://i.fishyfing.xyz/cogforthat.png)

**Comment by irdumbs** [comment]
that actually works great as the logo for the "beta" list O.o

can I just toss in there that the "beta" list has an increased security risk and that if you decided to install and run any code on your computer.... that's on you.

I'm hoping the "beta" list will become a sort of community in and of itself.
a group of developers making stuff, helping each other learn to code, helping the people that want to get onto the "approved" list, and **moderating themselves**. I mean, if you want it to be a nice list/community, you'd hopefully speak up about dangerous/breaking code in it.

**Comment by Eslyium** [comment]
Just some Ideas for the Beta list
1. Select people who yes or no the cogs/repo
2. Isn't a feature in the bot already
3. If its obvious its a code stolen from another cog and reworded Must credit (might be difficult)
4. Must have at least x amount of cogs before accepted.

Id honestly want it to be moderated and not just flooded with everyones repo. I get its all about having their repo up there but there has to at least be some guidelines/rules right?

**Comment by irdumbs** [comment]
well this list wouldn't be anywhere in the bot. It wouldn't be run by us either It'd be community-run... right?
so the only need for moderation would be self-moderation?

**Comment by Redjumpman** [comment]
+1

**Comment by franc-ist** [comment]
I like dumbs idea, but I'd be happy to moderate if need be

**Comment by Kowlin** [comment]
Instead of repo's for the beta. Let it be a per cog basis. Like you said we cant allow everyone to dump there stuff into it and expect to make it work.

**Comment by Redjumpman** [comment]
To expand on Kowlin's proposal, it could be a list like:

### **Supported Cogs**

_These cogs have very few or minor bugs , have been approved by the Mods_ 

Critera:
- Has been a Greenlight cog for at least X amount of time
- Has been approved by the mods
- No conflicts with Red
- Any bugs should be minor or cosmetic in nature.

### **Greenlight Cogs**

_These cogs need work. Updates are committed often, and users will need to check to make sure they have the current build._

Critera:
- Voted in by the Red community (x number of votes or by %. mod approves to Greenlight)
- Contains no malicious code  
- Does not conflict with Red  
- Does not replicate another cog

Just my 2¢, but I think it would be a really cool and engaging thing to have the community vote on cogs to be added to the Greenlight cog list. This is obviously subject to mod approval for obvious reasons, but it accomplishes two things. 1 it allows the community to be involved with cog creators for development and 2, it serves as a way of getting the community involved with the project for Red bot as a whole.
