### ISSUE TITLE
Repo approval request phantium-cogs

### ISSUE THREAD

**Issue by phantium** [Twentysix26/Red-Docs#24]
https://github.com/phantium/phantium-cogs

List: approved
Repository name: phantium-cogs
Author: Phantium
Description: Gaming related and other fun cogs

Hi there,

I started making cogs yesterday, I have finished my first cog which is for Overwatch.
I will be pushing out more cogs over the coming days/weeks and hopefully years. :)

I'd love for my repo to be added so I can share all of my cogs with others.

Cheers,
Phantium

**Comment by irdumbs** [comment]
keep adding/improving cogs and you'll get a 👍  from me

**Comment by phantium** [comment]
Thanks, I'll be adding more features to current cogs this week and adding new cogs as well.

**Comment by Eslyium** [comment]
Denying due to the following

At least 3 cogs. Exceptions can be made if one cog is complex / notable enough.

As well as no other cogs have been uploaded to be qualified for "Approved" feel free to add more cogs then try for the "Beta" List.
