### ISSUE TITLE
Beta-List cogs application

### ISSUE THREAD

**Issue by AznStevy** [Twentysix26/Red-Docs#25]
List: beta
Repository name: [Maybe-Useful-Cogs](https://github.com/AznStevy/Maybe-Useful-Cogs)
Author: Stevy
Description: One is a pretty large and I believe resource intensive cog for osu!, a whoplays cog, an omegle-like thing cause I thought it was cool, and a markov chain text generator.

**Comment by Redjumpman** [comment]
Can you add a link to your repo as well?

**Comment by AznStevy** [comment]
Done c:

**Comment by irdumbs** [comment]
mind using aiohttp instead of requests?
That way no blocking

**Comment by AznStevy** [comment]
I can try that. Also, it doesn't seem that the imagemagik thing is easily installable on Windows. Should this be concerning? Should I use pil instead?

**Comment by tekulvw** [comment]
Should you? yes, are we going to make you? no

**Comment by Twentysix26** [comment]
Approved for beta
