### ISSUE TITLE
calebj-cogs application

### ISSUE THREAD

**Issue by calebj** [Twentysix26/Red-Docs#27]
List: approved
Repository name: [calebj-cogs](https://github.com/neonobjclash/calebj-cogs)
Author: [CalebJ](https://github.com/neonobjclash)
Description: General and utility cogs I made or innovated upon.

**Comment by Redjumpman** [comment]
+1 from me. for w/e that's worth XD

**Comment by Dexthor** [comment]
+1 really love the timed mute! all my mods and bot commanders use it

**Comment by Twentysix26** [comment]
Still unsure if you have permissions from Kowlin and Mash to reupload their edited cogs with the same name. If you don't you'll have to change the name and credit the original authors (assuming you're reusing code)

**Comment by calebj** [comment]
I'll stub out the bartender with a link to Mash's repo, since my changes were merged there. The punish cog is completely rewritten and only has the same name as Kowlin's punish.

**Comment by calebj** [comment]
Alright, I've stubbed out bartender with directions to install from @Canule 's repo instead.

**Comment by Eslyium** [comment]
Or you can go ahead and just remove it from your Repo. That is a waste of time to go and download it then have to install a different Repo just to get it. People who have gotten it from your Repo where he was credited, They know where to look.

Thanks

**Comment by calebj** [comment]
After studying downloader.py, it became apparent that simply deleting the folder wouldn't remove it from downloader.py's data, and it would still attempt to install the cog from its former location in the repo. Without a fixed downloader.py, stubbing out bartender is the best solution.

I have Kowlin's permission, and Mash's cog is no longer an issue (even though I also had his permission).

**Comment by Twentysix26** [comment]
I'd still prefer if you just deleted the bartender cog (I'm aware of the current problem with the downloader and the fix will be merged once tested properly. So if you want to wait for that it's fine) and changed Punish to be its own thing. Punish is part of the default community repo (PR update pending) and you having a rewritten version only adds to the confusion.  
I mean, there's really no gain by not renaming it, people are less likely to use your cog thinking it's the same thing and it will conflict in case they have both. I'm willing to listen if you have any good reasons not to, though.  
Sorry for being pedantic but you _did_ apply for the approved list after all :smirk:

**Comment by calebj** [comment]
I've fixed downloader and the bot-killing issue when there are too many repos. PR is pending. That said, I've removed the bartender cog as well.

Regarding the punish name conflict: why would you have both installed? That would be dumb, and have duplicate triggers anyway.

I only had two or three cogs when I made this request. Now I have eleven, and lots of people are using them.

**Comment by Twentysix26** [comment]
👌
