### ISSUE TITLE
ax-cogs application

### ISSUE THREAD

**Issue by Aioxas** [Twentysix26/Red-Docs#33]
List: beta
Repository name: [Ax-cogs](https://github.com/Aioxas/Ax-Cogs)
Author: Aioxas
Description: Weird cogs that might or might not be useful for your needs. Check them out!

**Comment by Redjumpman** [comment]
You should add a MIT license to your repo, and in the readme you should put information explaining what your repo is about, maybe any lib requirements, etc. None of these are requirements just suggestions. +1

**Comment by Aioxas** [comment]
And half of what you said should be up in the repo right now. I might have to expand a bit on what the repo is, but apart from that, it should all be up or updated. Thanks for your suggestions.

**Comment by Twentysix26** [comment]
Approved for beta
