### ISSUE TITLE
palmtree5-cogs application

### ISSUE THREAD

**Issue by palmtree5** [Twentysix26/Red-Docs#35]
List: Beta
Repository name: [palmtree5-cogs](https://github.com/palmtree5/palmtree5-cogs)
Author: [palmtree5](https://github.com/palmtree5/)
Description: Various internet and Minecraft-related cogs

Applying for beta because tweets and reddit are still very much a work in progress

**Comment by franc-ist** [comment]
Rename the reddit class to `Reddit`, as this is used for loading and is easier if its the name of the cog. Otherwise, no problems.

**Comment by palmtree5** [comment]
Done with https://github.com/palmtree5/palmtree5-cogs/commit/b143a86f94b43f9d133b7261eb4ae63bd7185856

**Comment by Redjumpman** [comment]
First of all, good job on your readme and info.jsons. It's refreshing to see that done right the first time. Now on the the more troubling stuff. You have some syntax errors in your hpapi. Should be easy to fix. In some of your other cogs you have some unused imports. Especially that nasty unused discord import for your reddit cog.  That's my quick comb through. Good luck :palm_tree:

**Comment by palmtree5** [comment]
> You have some syntax errors in your hpapi.

Where specifically?

Also removed that unused discord import in the reddit cog, will go look for other unused imports some other time

**Comment by palmtree5** [comment]
Ok, after actually getting some things set up properly, I've removed unused imports and also fixed the syntax errors @Redjumpman was referring to

**Comment by Eslyium** [comment]
I wasn't sure I glanced at it but from my experience Reddit uses a user-name auth thing. If you have one default in there and tons of people use the cog that user-name will be blocked.

**Comment by palmtree5** [comment]
It uses an app key and app secret that is per reddit account and would be tied to that account. Also praw internally follows Reddit's rate limiting rules ([see this](https://praw.readthedocs.io/en/stable/pages/faq.html))

**Comment by palmtree5** [comment]
Ok, so since the last comment, I've added a couple of small cogs to the repo (`coventry` and `catfact`)

**Comment by Twentysix26** [comment]
👌
