### ISSUE TITLE
Rescans of repos.

### ISSUE THREAD

**Issue by franc-ist** [Twentysix26/Red-Docs#38]
Once a repo is approved, the author can add whatever cogs they like. This could potentially lead to a seemingly harmless repo having a malicious cog added in the future without us noticing.

I suggest we rescan repos a few times a month to prevent this.

**Comment by Twentysix26** [comment]
Honestly not much we can do about this, it was already discussed when we implemented the possibility of installing 3rd party repositories. That's why there's a huge disclaimer when you install new repos.  
But sure keeping an eye on them doesn't hurt

**Comment by franc-ist** [comment]
True. I'll close this.
