### ISSUE TITLE
Usage of last edited in header?

### ISSUE THREAD

**Issue by Kowlin** [Twentysix26/Red-Docs#4]
Should we consider using last_edited on the Markdown headers? as example, this would be Windows Requirements.

```

---
title: Windows requirements
sidebar: red_sidebar
permalink: /red_win_requirements/
last_edited: April 21, 2016

---
```

_Though I think we should use dd/mm/yyyy, but thats just my bias European opinion_

**Comment by irdumbs** [comment]
sure, why not?
I think we should be explicit about month, day, year, like in your example. `April 21, 2016`

**Comment by franc-ist** [comment]
i agree. [Month Name] [Day], [Year]
