### ISSUE TITLE
ridings-cogs Repo Application

### ISSUE THREAD

**Issue by ridinginstyle00** [Twentysix26/Red-Docs#40]
List: beta

Repository name: [ridings-cogs](https://github.com/ridinginstyle00/ridings-cogs)

Author: [Ridinginstyle00](https://github.com/ridinginstyle00)

Description: This repo adds in what I think would be some fun and useful little cogs. You have the Levels cog, which, if you know the bot that goes by the name of Mee6, then you know how his Leveling system works (when enabled). If you don't know Mee6, the Levels cog is basically a cog that, the more you chat, the more you gain EXP, and after a set amount of EXP, you level up. It's a fun little gag to see how much more you spam compared to your friends. Next is the Duels cog, that...well...lets you duel others! Although my code may look like crap for it. I tried my very hardest and accomplished the task. I even included an extra 30 actions from the first run! The third cog is the Commands cog. All it has is little commands that can be thrown around as joke commands. Some may find them very cruel and be labeled as harassment, but I find them fun things to use around. This cog also downloads the picture each time the command is called, which may cause some issues with slower internet. The last cog is the Dismissal cog. It works almost exactly the same way as irdumb's welcome cog (if I was informed correctly that was his cog), but instead of welcoming people...you guessed it, the Dismissal in fact shows a message when a specific person leaves the server. It was almost completely the same code. I changed it up though, I even updated it to dataIO instead of using the welcome cogs fileIO system. I give full props to irdumb and his code to aid me in making a dismissal cog.

If anyone finds any issues I overlooked, please tell me and I'll fix them ASAP!

**Comment by ridinginstyle00** [comment]
There are also some typos in the dismissal cog, that I haven't changed yet to actually match the dismissal cog. I'll try to get those fixed within the next few days.

EDIT:
I believe I got them all now.

**Comment by Eslyium** [comment]
Question.. I see you have your Commands cog uploading to files that the user normally wouldn't have 
"await self.bot.upload("data/commands/Images/imgres.png")"

I don't think this would work out really well if the user has to go and upload the file themselves due to most people are lazy :P

As well as can you explain to me what the "alertadd" command is for.

But I honestly don't get the point in this cog but feel free to explain it to me. x-x

**Comment by ridinginstyle00** [comment]
The cog auto downloads it each time. So that the file is always there whenever you run it. And to save space on the drive, I tried to restrict the use of multiple file names.  Imgres.jpg for example. 
The command auto uploads the files by itself when the command is called. I think that's what you're looking for there. And for alert add, it sets the roles that are used for alertmods. I just ran it and it seems one of my previous bugs picked back up, so I'll have to fix that when I can. 

Other than that. The commands cog is just used to auto post a few funny photos with their specified command. 

Pardon me for any typos I was doing this from phone. If I didn't explain something fully lemme know.

**Comment by Twentysix26** [comment]
You're saving the files to disk for no reason. You can upload them directly once loaded from the host.

**Comment by ridinginstyle00** [comment]
I saved them so that it removed the URL from the output. Unless I'm mistaken or a new discord update changed it, only uploaded pictures hide the  URL. 
If it has changed I can look into it here soon. I've been busy with a lot of things lately and haven't had much spare time.

**Comment by gtsatsis** [comment]
@ridinginstyle00 duels are broken, `Error in command 'duel' - KeyError: 'duels'`

**Comment by ridinginstyle00** [comment]
I'll go through tommorow and start fixing it up. I think that my data didn't upload properly. Causing some data errors here and there. I also think that the new discord updates are starting to mess up other cogs like the welcome cog. Or the set commands like set status and stream.

**Comment by ridinginstyle00** [comment]
@AsaPlaysMC Do you mind telling me which command you run to get that result, that way I can narrow down the issue.

**Comment by ridinginstyle00** [comment]
@AsaPlaysMC Have you updated it recently? I can't seem to find the issue with it myself. The new update adds in preset duels. If you already have that update, then you're good. If not, I recommend updating.

**Comment by Eslyium** [comment]
This is for wanting your repo on reds docs. Not for you to discuss issues with someones code cause you cannot use it. Go to his repo and report the issues there.

**Comment by AsaPlaysMC** [comment]
@ridinginstyle00 http://prntscr.com/cr99xa

**Comment by Twentysix26** [comment]
Cogs' filenames and folders must be lowercase.
You have `client = discord.Client()` in multiple cogs for absolutely no reason.
You initialize loggers even though you make no use of loggers whatsoever
You have loads of unused imports
Make a description for your repo of 2-3 lines maximum, that is too long to be put in the list in case it gets approved  

> I saved them so that it removed the URL from the output  

I know why you save them. What I was saying is that you can load them in memory and then send them directly as a filelike object without saving them to disk, which is unnecessary in your case.

**Comment by ridinginstyle00** [comment]
All righty. I'll get to work changing things and look into the memory function. And for @AsaPlaysMC could you please put a report on my repo. You put something here but it was taken down. (I got an email about the comment). So take Eslyium's advice and put it on my repo as an issue.

**Comment by Eslyium** [comment]
closing until further updates.
