### ISSUE TITLE
Dusty-Cogs application for approval

### ISSUE THREAD

**Issue by YeahImRose** [Twentysix26/Red-Docs#41]
List: beta

Repository name: Dusty-Cogs

Author: Awoonar Dust

Description: Cogs for server utilities and fun!

[Link to the repo](https://github.com/Lunar-Dust/Dusty-Cogs) *as a note, the cogs are still being developed, but I only push stable versions

**Comment by Twentysix26** [comment]
Classes names must be always CamelCase. Especially in the moji cog, where the command is the same name as the class.  
You can remove the opus dll checks, they have been bundled with discord.py for a long time now

**Comment by YeahImRose** [comment]
Fixed the casing issues and removed the opus checks.

**Comment by Twentysix26** [comment]
👌
