### ISSUE TITLE
shigbeard-cogs Application

### ISSUE THREAD

**Issue by Shigbeard** [Twentysix26/Red-Docs#45]
Well boy, here goes nothing. I only have one autistic cog in the repo, so I'm only going for beta. Expectations <= 0 == True

Currently, the only cog I've made allows any user to rate themselves or another user using emoji (see Facepunch.com, you can rate posts). I intend to make more changes in the near future, however if you look at my other main repo, you can see intentions don't often get carried out. Currently I am trying to come up with some original cog ideas, thinking maybe a source engine server info thingo

List: beta

Repository name: [shigbeard-cogs](http://github.com/Shigbeard/shigbeard-cogs)

Author: Me, Shigbeard.

Description: Literally just a place where I will put some meme-level cogs that I make.

**Comment by Twentysix26** [comment]
Needs more content, see requirements. I'll leave it open in case you add more cogs in the near future.

**Comment by Shigbeard** [comment]
Yeah, I plan to. Just need to finish this one first.

**Comment by Shigbeard** [comment]
Closing this, I doubt I'll have a new cog or two that isn't a 20 second crapfest any time soon. I'll reopen when I have more content.

Especially as I'm making sure this one cog I have is polished and ready to ship before I start thinking about another.
