### ISSUE TITLE
Scarlet-Cogs

### ISSUE THREAD

**Issue by ScarletRav3n** [Twentysix26/Red-Docs#48]
**List**: Beta/Approved

**Repository name**: [Scarlet-Cogs](https://github.com/ScarletRav3n/Scarlet-Cogs)

**Author**: ScarletRav3n

**Description**: Fun and random cogs for general entertainment.

**Comment by NekoTony** [comment]
Love this

**Comment by Twentysix26** [comment]
Approved for beta list
