### ISSUE TITLE
Snap-ons

### ISSUE THREAD

**Issue by SnappyDragon64** [Twentysix26/Red-Docs#49]
List: beta

Repository name: [Snap-ons](https://github.com/SnappyDragon18/Snap-ons)

Author: SnappyDragon18

Description: Cogs based on nerd-culture and games for Red-Discord Bot.

**Comment by SnappyDragon64** [comment]
It's been 26 days...

**Comment by Redjumpman** [comment]
We are working towards a completely redesigned system for applications. Until that time, applications will be on hold. We are close to finishing, what will be a great system that I am sure you and many other content creators will be happy with. In the interim, continue working on your code, testing your work, and perfecting your technique. We will make an announcement when everything is finished. Thank you for your **continued** cooperation and **patience**.

**Comment by SnappyDragon18** [comment]
~~lol it was a pun~~

**Comment by SnappyDragon64** [comment]
I was making a 26 Twentysix pun. :P

**Comment by SnappyDragon64** [comment]
Fixing up old cogs, Deleted a few.
-Island Challenge is gone.
-Fictional Currency is gone.
-Changed all dicts to be lists.

**Comment by SnappyDragon64** [comment]
Working on a new cog- FNAF.

**Comment by SnappyDragon64** [comment]
FNAF has been uploaded. (Now deleted.)
When will my repository be reviewed?

**Comment by SnappyDragon64** [comment]
PlantTycoon is being constantly updated :D

**Comment by SnappyDragon64** [comment]
Floette, it's been 3000 years, uhm, I mean, 5 months.

**Comment by SnappyDragon64** [comment]
Moved all format() in interactions to the bot.say() statements.

**Comment by SnappyDragon64** [comment]
Removed all commands but adventcalendar and trickortreat from seasonal for being useless.

**Comment by Twentysix26** [comment]
Add a `REQUIREMENTS` field to info.json in cogs that need pip libs to be installed. Example:
`"REQUIREMENTS" : ["cleverbot"],`

**Comment by SnappyDragon64** [comment]
I added the ``REQUIREMENTS`` field to the love calculator cog, which uses beautiful soup 4.

**Comment by SnappyDragon64** [comment]
Changed repository name.

**Comment by Twentysix26** [comment]
There are minor nitpicks but I think being in approval limbo since october is enough. Approved for beta
