### ISSUE TITLE
Sentry-Cogs

### ISSUE THREAD

**Issue by Jan200101** [Twentysix26/Red-Docs#50]
List: Approved [Or Beta]

Repository name: [Sentry-Cogs](https://github.com/Jan200101/Sentry-Cogs)

Author: Sentry

Description: Usefull Cogs that have a tendency to shoot at you

**Comment by palmtree5** [comment]
Issues:
- the say command in say conflicts with the one in @tekulvw's admin cog
- the discord link given on adding the repo is expired (should probably be a permanent one as opposed to a temp one)
- your cog info.json files need to be named info.json, not cog info.json
- remove `import discord` from all cogs except channelinfo and info

**Comment by Jan200101** [comment]
I wasnt aware that there was a say command in tekulvw's admin cog. I am going to see what I can do there

The Discord link is expired as it was seen as a test. Right now I am trying to tidy my repo up.

Yes I know I forgot that part

Okay. I was not aware that discord was not needed for all cogs

**Comment by Jan200101** [comment]
Made say not load when admin is loaded

Link has been replaced and should be permanent now

Changed names of the files

Removed Import

**Comment by Twentysix26** [comment]
All class names should be CamelCase  
All folder names and file names should be lowercase
I suggest to move experimental stuff to a different branch
All cogs should have an info.json. I see some are even incorrect

**Comment by Jan200101** [comment]
Changed (I think) all class names to CamelCase
folder names are all now lowercase
experimental stuff is not in a beta branch
all other cogs have a info.json
fixed (I think) all incorrect info.jsons

**Comment by Jan200101** [comment]
Okay some cogs I didnt remove randomly disappeared.... Im gonna try fixing that

**Comment by Jan200101** [comment]
fixed the previous error and added a README.md

**Comment by Twentysix26** [comment]
Your mathematics cogs has an open eval in it. FYI this gives the ability to users to run arbitrary code on the host.
To be honest there's an alarming rate of "I don't know what I'm doing" in this repo, both on the code side and the git side of things, just by looking at your commit list.  
Furthermore, a lot of your cogs seem *very* limited in usefulness or just plain useless (`isloaded`).  
I'd rather accept a repo with 3 cogs that bring something a bit useful / fun than one with 10 cogs with functions that are basically like the ones in default.

I'm going to deny this for now, you can reapply at a later date when you sort most of this out.
