### ISSUE TITLE
better cog-making tutorial? / red conventions

### ISSUE THREAD

**Issue by Chovin** [Twentysix26/Red-Docs#52]
The quality of cogs coming from newcomers isn't increasing and it doesn't seem like they're getting better any faster than the newcomers from awhile ago. This means cogs coming from our community isn't getting any better in quality as time passes.
We're getting saturated with cogs that are just random messages and posting images.

I blame partly our lack of a good tutorial. You can argue that one isn't needed, but it seems rather difficult for newcomers to understand how the community works and how the conventions around here work.

Currently we got: https://twentysix26.github.io/Red-Docs/red_guide_make_cog/
and unofficially: https://github.com/FreeCodeCampGuam/FreeCodeCampGuamHelp/blob/master/Python/README.md

should we get together and make some effort to put down a decent tutorial and write down all our conventions in a more accessible way?

**Comment by skeith** [comment]
Speaking from experience, if we asks the python gods, it's either tag learnpython or google

Well, it's not like I am lazy, but (yeah reasoning do makes me admit that I am lazy) with tutorial from the python gods, gives us confidence

**Comment by Kowlin** [comment]
I think most of us can agree that the current official cog guide needs a rework. but what will we expect from the user to know. (*Insert common sense joke*) And what will we explain. Most new cog creators didn't know what a module was until it was explained to them.

**Comment by Twentysix26** [comment]
Most of the conventions are based on python's own pep8.  

I do absolutely agree that a better tutorial would be good, even just to show how cogs are structured.  
The current one doesn't even mention `context` but instead goes over web scraping, that's over the head of anyone starting with coding.  

We don't need to make a guide on how to code, there are enough resources around, but one about the inner workings of the command ext is enough

**Comment by skeith** [comment]
... and the reasoning Kowlin keep shouting "you did not need import discord" while his cog has import discord

Forgive me if this is wrong though

**Comment by palmtree5** [comment]
I agree the guide shouldn't necessarily go over basic coding (other than perhaps pointing to resources for people who want to learn to code) but that it should go into more detail about usage for the things Twentysix mentioned.

**Comment by Kowlin** [comment]
I'll agree with this. This seems like a good way to start of the new series of guides.

Edit: for those willing to make a PR, I'll assign you to this issue then.
