### ISSUE TITLE
[Community Repo] Nop0x Cogs

### ISSUE THREAD

**Issue by mkilp** [Twentysix26/Red-Docs#57]
List: [beta] (approved if you think I'm worth it)
Repository name: https://github.com/Nop0x/Nop0xcogs
Author: Nop0x
Description: Several Cogs around countries and timezones.

Commands added:
-addcountry : Sets your country of origin and stores it in a json.
-removecountry : removes your country of origin.

-locate: prints which countries a user has set.
-location: pms all users for a given location
-location_settings: settings for the heatmap functionality
-map: generates a heatmap where users are from and uploads it to a channel

-timezone user: print the current time of the user who is issuing the command
-timezone user : prints the current time of a given user
-timezone_settings: settings needed for the timezone command

Any feedback is appreciated!

If you have questions hmu on discord Nop0x#4618 or comment here :)

**Comment by Twentysix26** [comment]
Class names should be CamelCase
Remove `requests` from your imports. It's blocking, 3rd party and you are not even using it
To each cog's info.json add a `"REQUIREMENTS"` field. It's going to be a list that contains 3rd party libs required by your cog. The downloader will automatically install them.  
Example:
`"REQUIREMENTS" : ["tabulate", "pytz"]`

**Comment by mkilp** [comment]
@Twentysix26 I fixed all your points in my latest commit.
Downloader doesnt seem to download the requirements properly though :/

**Comment by mkilp** [comment]
problems are fixed now (re: our discord chat)
also fixed some problems with dependencies, removed requests along with other unused imports.
cleaned up the code!

**Comment by Kowlin** [comment]
The problems you've fixed seem alright, however after doing a quick scan my self I found the following:
[Unused json import](https://github.com/Nop0x/nop0xcogs/blob/master/countrycode/countrycode.py#L2),
[Unused json import](https://github.com/Nop0x/nop0xcogs/blob/master/location/location.py#L1)
and finally, another [unused json import](https://github.com/Nop0x/nop0xcogs/blob/master/timezone/timezone.py#L2)

Will pass it along to 26.

**Comment by mkilp** [comment]
@Kowlin I think I removed the unused reports now. Hope my code survives another check. Let me know if you find anything else!

**Comment by mkilp** [comment]
Anything else left which keeps me from being moved to beta?(:
