### ISSUE TITLE
ORELS-Cogs

### ISSUE THREAD

**Issue by orels1** [Twentysix26/Red-Docs#58]
List: approved

Repository name: [ORELS-Cogs](https://github.com/orels1/ORELS-Cogs)

Author: orels1

Description: Gaming / data based cogs, with a bit of some fun stuff

**Comment by NekoTony** [comment]
Nice repo

**Comment by Jan200101** [comment]
👍

**Comment by Redjumpman** [comment]
Please limit comments in applications to constructive feedback or issues in the code. If you want to express that you like a repo or to show support a +1 is enough.

**Comment by ghost** [comment]
This may conflict with my Steam cog.

**Comment by Twentysix26** [comment]
Some of your cogs' info.json are missing the "SHORT" field.  
Anyway, 👌
