### ISSUE TITLE
Rework all instalation docs

### ISSUE THREAD

**Issue by Kowlin** [Twentysix26/Red-Docs#6]
With the bot changes and so on the installation page has become a giant mess, I've started working on a new branch that covers all the new installation methods, new pages and an amazingly revamped home page (Yes I'm making this one shiny text). Below is a list of the things that are needed to be done
- [ ] New home page
- [ ] Pre installation guide (covers creating bot or user account) 
- [ ] Windows guide
- [ ] Linux (Debian) guide
- [ ] Linux (Fedora) guide
- [x] Approved (Placeholder name) Repo list
- [x] Guide on adding the approved repo's

**Comment by FishyFing** [comment]
Approved.

**Comment by irdumbs** [comment]
Mac install could probably be easily made into .command or .py file that'll install all the prereqs and the bot.
