### ISSUE TITLE
Paddo-Selfbot

### ISSUE THREAD

**Issue by ghost** [Twentysix26/Red-Docs#61]
List: beta 

Repository name: [Paddo-Selfbot](https://github.com/PaddoInWonderland/Paddo-Selfbot)

Author: Paddo

Description: Various cogs for selfbots only.

**Comment by Twentysix26** [comment]
This is quite original. I'm slightly worried about it ending up on https://cogs.red and people running it on normal bots though.

How about you check in the setup function that it's effectively being run by a selfbot? We have a `Bot.settings.self_bot` flag

**Comment by Kowlin** [comment]
Does this check apply on Caleb's branch though?

**Comment by ghost** [comment]
I could add that flag, yes.

**Comment by ghost** [comment]
I have updated all cogs to check for the `Bot.settings.self_bot` flag.
