### ISSUE TITLE
RiceCogs

### ISSUE THREAD

**Issue by QingyuChai** [Twentysix26/Red-Docs#64]
Hello! I'd like to apply to have my repo become beta.

List: [beta]
Repository name: RiceCogs
Author: FwiedWice
Description: Random cogs ranging from server management to utility to killing people.

https://github.com/QingyuChai/RiceCogs

**Comment by Twentysix26** [comment]
`rice` cog: Custom stuff that doesn't belong in a public repo  

[This](https://github.com/QingyuChai/RiceCogs/commit/7a30e71522d0206dfa5ccbdb55a91c20fff1735d#diff-cb460ae5c59198c5ee4c801ae2d26d50R98)... just no, you shouldn't depend on the user to start a loop that makes your cog function. Even if you want to make it optional, it should be designed better, at the moment it won't even stop if the cog gets unloaded.

Your `code` cog could be one liners or just a single command if you use the `box` function in utils/chat_formatting

**Comment by QingyuChai** [comment]
@Twentysix26 sorry, I didn't see your comment until now! I'll find a way to fix the birthday loop.

**Comment by Kowlin** [comment]
Spotted this part when browsing your repo. You might want to grab the server prefix. https://github.com/QingyuChai/RiceCogs/blob/master/birthday/birthday.py#L96

**Comment by QingyuChai** [comment]
@Kowlin thank you, Kowlin! I will be changing this for all of my cogs!

**Comment by Chovin** [comment]
@Kowlin @QingyuChai can you explain to me why you'd want to do that?
`ctx.prefix` is the prefix used to call the command. I see no problem with using that to tell people what to type next

**Comment by QingyuChai** [comment]
That's what I just changed @Chovin

**Comment by Chovin** [comment]
ahh.. see, if this was a PR, I'd be able to see that :P 😭

**Comment by QingyuChai** [comment]
@Twentysix26 Hey! I removed the rice cog from the repo, and for birthday I decided that the user would still have to start the loop if he wants it. However, the loop now stops when the cog is unloaded and the owner cannot start multiple loops. Also, for the code cog, I did what you recommended, and it works perfectly! Thanks!

**Comment by QingyuChai** [comment]
I haven't really been maintaining RiceCogs as well as I should have, and I am not satisfied with the quality of what I have made. I will be closing this issue for now, and will reopen it once I created better content.
