### ISSUE TITLE
Docs showing Python 3.5.1

### ISSUE THREAD

**Issue by palmtree5** [Twentysix26/Red-Docs#66]
### [Windows install](https://twentysix26.github.io/Red-Docs/red_install_windows/#software)
![](https://cloud.githubusercontent.com/assets/17536161/22191330/6b2e7444-e175-11e6-84da-47e405eee12d.png)

**Comment by palmtree5** [comment]
https://github.com/Twentysix26/Red-DiscordBot/issues/587

**Comment by Kowlin** [comment]
I can get that this is a thing, but I don't think this is critical. Only due the fact that well... It still does what's its supposed to do. Show the user that they need to check the path.

**Comment by Chovin** [comment]
I disagree.
Nowhere in that doc does it say which version you should get. just "3.5"
the picture shows 3.5.1, so *shrug

**Comment by Redjumpman** [comment]
Just tell the user to download latest python version 3.5.x. that way it is timeless and will work for any future RC.

**Comment by Chovin** [comment]
3.5 or above includes 3.5.1 which doesn't work with Red.
issue not resolved

**Comment by palmtree5** [comment]
What. Why does 3.5.1 not work with red? Does 3.5 work with Red? I know 3.5.2 works

**Comment by Twentysix26** [comment]
>or above includes 3.5.1 which doesn't work with Red.  

[citation needed]
