### ISSUE TITLE
FlapJack-Cogs

### ISSUE THREAD

**Issue by flapjax** [Twentysix26/Red-Docs#70]
List: Beta
Repository name: [FlapJack-Cogs](https://github.com/flapjax/FlapJack-Cogs)
Author: FlapJack
Description: Cogs containing features such as sfx, reaction polls, game utilities, name color management, triggered emoji reactions, a server DEFCON system, and dongers.

I've recently put a lot of work into testing, documentation, and PEP 8 compliance, and I'm ready to submit this repo for beta status.

**Comment by Twentysix26** [comment]
Your application is for the beta list but I see a lot of quality content and effort in your repo. "Approved" list it is 👍
