### ISSUE TITLE
NationCogs

### ISSUE THREAD

**Issue by Zephyrkul** [Twentysix26/Red-Docs#71]
List: beta
Repository name: [NationCogs](https://github.com/zephyrkul/NationCogs)
Author: Zephyrkul
Description: Useful user-friendly commands to get general [NationStates](https://www.nationstates.net/) information, as well as less-useful, less-userfriendly (but still documented) commands to get specific NationStates information. Also includes a fun little cog to have the bot say a random guard line from Skyrim.

**Comment by Zephyrkul** [comment]
Since this repo is pretty small and I hope to add more to it, I switched my application to Beta for now. When my repo is more fleshed out I'll reapply for Approved.

**Comment by Zephyrkul** [comment]
I don't know if this has been looked at yet or not, but as a note, I just pushed a big update to it. Were it not for one big issue, I'd think it's ready for Approved status.
That big issue is: the library I'm using blocks due to the use of requests and time.sleep()...
So until I fix that and add a couple more planned cogs I'll leave this application in beta.

**Comment by Twentysix26** [comment]
I don't play NS but I see 5 small sized cogs for different aspects of one game. Perhaps it would be better to merge the functionalities in one? Or is there any reason you have them split?

**Comment by Zephyrkul** [comment]
That may actually be a good idea. I likely kept them separate for some attempt at modularity, but from what I've seen of its use cases, it seems all of them are loaded together. I'll talk to my current (small) userbase about it, then add other cogs I'm planning on adding to bring it back above the three cogs minimum threshold.
