### ISSUE TITLE
Scarlet-Cogs

### ISSUE THREAD

**Issue by ScarletRav3n** [Twentysix26/Red-Docs#73]
**List:** Approved

**Repository name:** https://github.com/ScarletRav3n/Scarlet-Cogs

**Author:** ScarletRav3n

**Description:** Fun and random cogs for general entertainment.

Gotta do it for Grammar.py and TitleCase.py

**Comment by Twentysix26** [comment]
Please no more globals and no more single letter variables

**Comment by ScarletRav3n** [comment]
Fixed and fixed
