### ISSUE TITLE
PTSCogs

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [Twentysix26/Red-Docs#76]
Yep, another one with the word 'cogs' in it, I'm so original.

List: Approved

Repository name: https://github.com/PlanetTeamSpeakk/PTSCogs

Author: PlanetTeamSpeak

Description: Loads of cogs that may or may not be useful.

I have a fuck ton of cogs, 29 to be exact. The README is not complete yet but I am working on it (haven't updated it in a month).

**Comment by Twentysix26** [comment]
Needs a major cleanup. You have stuff in there that it's not even yours, which might also go against the licenses of the individual repos you took those from.
At the moment it looks more like a dumping ground rather than a repo made to share your work with the public.
No go for either lists.
