### ISSUE TITLE
Gelato-Cogs

### ISSUE THREAD

**Issue by softgrass** [Twentysix26/Red-Docs#77]
# Gelato-Cogs
```
List: beta
Repository name: gelato-cogs
Author: Gellato
Description: Just A Bunch Of Fun and Random Cogs.
```
[https://github.com/gellatio/gelato-cogs/](
https://github.com/gellatio/gelato-cogs/ )

**Comment by Twentysix26** [comment]
Way too low on content for now. Leaving the issue open, post again when you have some updates

**Comment by Twentysix26** [comment]
Closing since you deleted your repo and left the server.
