### ISSUE TITLE
SinbadCogs

### ISSUE THREAD

**Issue by mikeshardmind** [Twentysix26/Red-Docs#79]
List: [beta] or [Approved]
Repository name: https://github.com/mikeshardmind/SinbadCogs
Author: mikeshardmind
Description: Bunch of additional features people have wanted.

**Comment by Aioxas** [comment]
Please read the repo publishing instructions first, you need a minimum of 3 cogs in order to apply.

Here's a link to them: https://twentysix26.github.io/Red-Docs/red_cog_how_to_publish/

**Comment by mikeshardmind** [comment]
I read them,
"Exceptions can be made if one cog is complex / notable enough.",
I was hoping this would qualify, but if not, I'll be happy to reapply when I add more.

**Comment by mikeshardmind** [comment]
I'm now at three working cogs. I'll be adding more as my needs demand, this is more a "hey I made this and other people might find it useful" thing for me.

**Comment by Twentysix26** [comment]
I noticed you left the server. Are you still interested in this?

**Comment by mikeshardmind** [comment]
Something unexpected happened and I don't have the time to maintain this. People are still welcome to use what I've written, but I should have closed this request.

**Comment by mikeshardmind** [comment]
I have more spare time again and have been developing a bit more. Looking to resubmit with a handful more cogs than I had before.

**Comment by mikeshardmind** [comment]
Bump?
