### ISSUE TITLE
Repo Approval - Dumb-Cogs

### ISSUE THREAD

**Issue by irdumbs** [Twentysix26/Red-Docs#8]
https://github.com/irdumbs/Dumb-Cogs

I also suggest using optional info.json files in the root directory for more info on the repo itself :3
Can probably just delete the DISABLED item in that info.json though

Repository name: Dumb-Cogs
Author: irdumb
Description: Example cogs as well as various silly, QOL, and community-based cogs

**Comment by Kowlin** [comment]
Please provide a description.

**Comment by irdumbs** [comment]
updated master Kowlin 👍

**Comment by irdumbs** [comment]
![image](https://cloud.githubusercontent.com/assets/15660809/14841613/dd629f7c-0c82-11e6-993e-33e32e3a6abe.png)
woo boy i must have been tired
