### ISSUE TITLE
Red Install script

### ISSUE THREAD

**Issue by palmtree5** [Twentysix26/Red-Docs#85]
I made this script that allows the user to just run it as root or with sudo but then runs through the install process. It includes all of the linux distros that currently have docs, as well as Mac. It doesn't currently include raspbian but that will be added soon. https://github.com/palmtree5/red-install

Testing status:

- [ ] Alpine
- [x] Archlinux
- [ ] CentOS 7
- [ ] Debian 8
- [ ] Fedora 25
- [ ] OpenSUSE 42.2
- [ ] OSX
- [ ] Raspbian
- [x] Ubuntu 16.04

**Comment by palmtree5** [comment]
There's also probably a number of enhancements that could be made to this as well (for example: autogen of a file for autostart, possibly pregenning the config file)

**Comment by palmtree5** [comment]
Ok, Raspbian's in now

**Comment by Jan200101** [comment]
Tested Raspbian, works fine

**Comment by MGStan0** [comment]
pi
