### ISSUE TITLE
Repository approval of PaddoCogs

### ISSUE THREAD

**Issue by ghost** [Twentysix26/Red-Docs#9]
Repository name: PaddoCogs (https://github.com/PaddoInWonderland/PaddoCogs)
Author: PaddoInWonderland (Paddolicious#8880 on Discord)
Description: General cogs I developed.

**Comment by franc-ist** [comment]
@PaddoInWonderland you are missing info.json for all the cogs

**Comment by Kowlin** [comment]
@FishyFing they arn't required.

**Comment by Kowlin** [comment]
@PaddoInWonderland There is 1 conflicting issue that needs to be resolved. Your Poll cog will cause a error when used together with General. This is caused due general already having a poll command. 

Besides that, I vote for your work. Will pass it onto the others.

**Comment by ghost** [comment]
I will omit the poll cog for the time being.

**Comment by irdumbs** [comment]
you could rename it 😉

**Comment by ghost** [comment]
Or that... :)

**Comment by tekulvw** [comment]
You need to name and specify the command arguments, not just have a tuple called `arguments`, so users can know what they need to enter. Referencing [this](https://github.com/PaddoInWonderland/PaddoCogs/blob/master/experience/experience.py#L92) specifically. Fix that and I'd give you my +1

**Comment by Kowlin** [comment]
As soon as you fixed the `poll` command then you have my +1

**Comment by ghost** [comment]
@tekulvw Fixed all `arguments` tuples.

@Kowlin `poll` is now named `vote`

**Comment by Kowlin** [comment]
We have a slight issue with the `*argumen tumples` you use, its best to rework them in something else.

**Comment by irdumbs** [comment]
^ referencing stuff like [this](https://github.com/PaddoInWonderland/PaddoCogs/blob/master/experience/experience.py#L80)

should be something like [this](https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/alias.py#L22)

**Comment by tekulvw** [comment]
I agree, split up `*arguments` into the actual arguments in the function
definition, not just in the docstring.

**Comment by ghost** [comment]
Alright, [updated](https://github.com/PaddoInWonderland/PaddoCogs/blob/master/experience/experience.py#L80). I could not avoid this with the vote cog, however, because [I cannot split the arguments](https://github.com/PaddoInWonderland/PaddoCogs/blob/master/vote/vote.py#L63-L81).

**Comment by ghost** [comment]
Anyone reviewing still? :smile:

**Comment by irdumbs** [comment]
tiny tiny things
some people may be confused with the vote instructions. could you please put an example like poll does

```
Usage example:
        poll Is this a poll?;Yes;No;Maybe
        poll stop
```

I'm curious what the purpose of invoice is :3 why would someone need an in_voice role?

tiny tiny tiny things
logtools help strings are kind of lacking. they just repeat the args that people will get if they do `!help logs get` anyway.

I don't understand why you have an entirely new command named `!logs roleplay` if it does the exact same thing as `!logs get` except without the users' mentions.

why are you saving mentions if they don't work in files?

**Comment by ghost** [comment]
> some people may be confused with the vote instructions. could you please put an example like poll does

I'm omitting poll for the time being anyway, it has some weird behavior going on that I have yet to debug.

> I'm curious what the purpose of invoice is :3 why would someone need an in_voice role?

It gives a voice user the 'voice' role. Maybe I should make it more dynamic as the bot owner could choose the role they want. I made this for my own server, where only voice users can use the #voice text channel. 

> I don't understand why you have an entirely new command named !logs roleplay if it does the exact same thing as !logs get except without the users' mentions.

Roleplayers would like to see a cleaner output for their logs.

> why are you saving mentions if they don't work in files?

For legacy' sake. ^_^

**Comment by irdumbs** [comment]
It's not an issue with approval, so I give my +1,
but it'd make me feel better if you combined `get` and `roleplay` into one command. you know, just make an option to turn mentions on, or allow people to give their own format.

**Comment by ghost** [comment]
That will certainly go on my todo list.

**Comment by ghost** [comment]
Any progress in the review process?

**Comment by franc-ist** [comment]
@PaddoInWonderland did you do the combination of the commands?

**Comment by ghost** [comment]
@FishyFing 

I omitted the vote cog, there's stil some issues with it I cannot resolve due to time constraints.

**Comment by franc-ist** [comment]
@PaddoInWonderland you had 10 days to combine a command lol

**Comment by ghost** [comment]
¯\_(ツ)_/¯

**Comment by irdumbs** [comment]
I'll be happy to help out if you ask in the Red server.
Like I said, it's not an issue with approval for me though.
Can we get one more look and subsequent +1 here?

**Comment by franc-ist** [comment]
I'm fine with it @irdumbs

**Comment by Twentysix26** [comment]
:+1:

**Comment by irdumbs** [comment]
one last thing.
https://github.com/PaddoInWonderland/PaddoCogs/blob/master/experience/experience.py#L88
~~set()~~ :/ but not an issue
https://github.com/PaddoInWonderland/PaddoCogs/blob/master/experience/experience.py#L106
~~!ignore~~ subcommand. not an issue
please fix these.

**Comment by RustyRaptor** [comment]
Well I guess no more PaddoCogs.
