### ISSUE TITLE
MaffiesCogs Application

### ISSUE THREAD

**Issue by jorivanee** [Twentysix26/Red-Docs#91]
List: Approved
Repository name: https://github.com/JustMaffie/MaffiesCogs
Author: JustMaffie
Description: MaffiesCogs is a directory of cogs created by JustMaffie (me)

**Comment by palmtree5** [comment]
Would very much recommend putting descriptive docstrings for both the class and the command functions (since that's where the info for the help command is pulled from)

**Comment by jorivanee** [comment]
Will do, sorry, always forget that

**Comment by jorivanee** [comment]
Added them

**Comment by skeith** [comment]
grammar issue on lockedchannels

**Comment by jorivanee** [comment]
fixed
