### ISSUE TITLE
For now just a VidMe cog

### ISSUE THREAD

**Issue by LazyHatGuy** [Twentysix26/Red-Docs#93]
List: beta
Repository name: https://github.com/TheLazyHatGuy/ShitPostCogs
Author: TheLazyHatGuy
Description: Some cogs from my bot ShitPost.EXE

**Comment by LazyHatGuy** [comment]
I updated the repo but I can't find any of my cogs when I search for them. Have I missed something or is my repo just not fully registered yet?

**Comment by palmtree5** [comment]
Leave a comment on orels1/Red-Portal/issues/3 to request being added to http://cogs.red

**Comment by LazyHatGuy** [comment]
Still no luck it seems?
