### ISSUE TITLE
mining_d-Cogs

### ISSUE THREAD

**Issue by ghost** [Twentysix26/Red-Docs#94]
List: beta
Repository name: [mining_d-Cogs](http://github.com/mining-d/mining_d-Cogs)
Author: mining-d
Description: my cog to learn python (German)

**Comment by ghost** [comment]
I don*t know why I make a label

**Comment by Twentysix26** [comment]
Please reconsider applying when you have content that could be useful to someone other than yourself.

**Comment by ghost** [comment]
I have translate my Cog sursefully

**Comment by ghost** [comment]
What must I do so that my cog?

**Comment by Jan200101** [comment]
Dein 'cog' ist nicht universel gedacht sondern ist nur für dich nützlich, nicht für andere.

**Comment by ghost** [comment]
wieso

**Comment by Jan200101** [comment]
Wenn du eine Repo hier als Angenommen haben möchtest müssen sie nicht nur and dich gerichtet sein sondern an alle.
Was habe ich für einen Nutzen wenn ich dein cog installiere ?

**Comment by ghost** [comment]
Du hast *fun* commands und ich werde diesen cog immer wieder Aktualisieren

**Comment by Twentysix26** [comment]
Regardless of the status of the current cog you have there is not nearly enough content to be considered for approval. Locking.
