### ISSUE TITLE
3D-Cogs

### ISSUE THREAD

**Issue by ghost** [Twentysix26/Red-Docs#97]
List: beta
Repository name: https://github.com/Northern3D/3D-Cogs
Author: Northern3D
Description: It's one cog. ao3. There are _no discord bots in existence_ that support ao3. I believe this will be heavily used by fan-fiction/fandom discord servers.

It works with every fanfiction on ao3 with no crashes.
The code is clean with _very minimal_ to no spaghetti.
[It has a clean, polished look.](http://i.imgur.com/cr6ERgB.png)

**Comment by tekulvw** [comment]
1) The `ao3` library you're using makes use of requests which means it's unsuitable for use inside Red.
2) I'm sure you're aware of the rule of 3, but if not, we do require new repos to have at least 3 meaningful cogs prior to consideration.

Thanks for applying!
